export const MateData = [
  {
    Selected: false,
    CompanyName: 'Tagcat',
    Country: 'United Kingdom',
    Name: 'Classic Vest',
    SellDate: '11/10/2025',
    Phone: '01-2331942',
    InStock: true,
    Quantity: 172,
    OrderID: 2,
    B: 2,
  },
  {
    Selected: true,
    CompanyName: 'Zoomzone',
    Country: 'Indonesia',
    Name: 'Cycling Cap',
    SellDate: '03/05/2025',
    Phone: '88-2768633',
    InStock: true,
    Quantity: 188,
    OrderID: 6,
    B: 2,
  },
  {
    Selected: true,
    CompanyName: 'Meeveo',
    Country: 'United States',
    Name: 'Full-Finger Gloves',
    SellDate: '27/03/2025',
    Phone: '51-6775945',
    InStock: true,
    Quantity: 162,
    OrderID: 1,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Buzzdog',
    Country: 'Philippines',
    Name: 'HL Mountain Frame',
    SellDate: '29/08/2025',
    Phone: '44-4028109',
    InStock: true,
    Quantity: 133,
    OrderID: 7,
    B: 1,
  },
  {
    Selected: true,
    CompanyName: 'Katz',
    Country: 'India',
    Name: 'Half-Finger Gloves',
    SellDate: '02/10/2025',
    Phone: '08-2758492',
    InStock: true,
    Quantity: 87,
    OrderID: 1,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Jaxbean',
    Country: 'China',
    Name: 'HL Road Frame',
    SellDate: '28/09/2025',
    Phone: '84-3557705',
    InStock: false,
    Quantity: 26,
    OrderID: 8,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Wikido',
    Country: 'Brazil',
    Name: 'HL Touring Frame',
    SellDate: '24/06/2025',
    Phone: '20-9397637',
    InStock: false,
    Quantity: 110,
    OrderID: 4,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Browsedrive',
    Country: 'United States',
    Name: 'LL Mountain Frame',
    SellDate: '13/03/2025',
    Phone: '36-0079556',
    InStock: true,
    Quantity: 50,
    OrderID: 4,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Twinder',
    Country: 'United Kingdom',
    Name: 'LL Road Frame',
    SellDate: '06/04/2025',
    Phone: '41-1489542',
    InStock: false,
    Quantity: 160,
    OrderID: 6,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Jetwire',
    Country: 'China',
    Name: 'LL Touring Frame',
    SellDate: '01/02/2025',
    Phone: '37-1531629',
    InStock: true,
    Quantity: 30,
    OrderID: 8,
    B: 5,
  },
  {
    Selected: false,
    CompanyName: 'Chatterpoint',
    Country: 'China',
    Name: 'Long-Sleeve Logo Jersey',
    SellDate: '14/07/2025',
    Phone: '25-5083429',
    InStock: true,
    Quantity: 39,
    OrderID: 7,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Twinder',
    Country: 'Egypt',
    Name: "Men's Bib-Shorts",
    SellDate: '31/08/2025',
    Phone: '04-4281278',
    InStock: false,
    Quantity: 96,
    OrderID: 6,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Midel',
    Country: 'United States',
    Name: "Men's Sports Shorts",
    SellDate: '27/06/2025',
    Phone: '55-1711908',
    InStock: true,
    Quantity: 108,
    OrderID: 10,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Yodo',
    Country: 'India',
    Name: 'ML Mountain Frame',
    SellDate: '16/03/2025',
    Phone: '58-8360815',
    InStock: false,
    Quantity: 46,
    OrderID: 1,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Camido',
    Country: 'Russia',
    Name: 'ML Mountain Frame-W',
    SellDate: '13/09/2025',
    Phone: '10-3786104',
    InStock: true,
    Quantity: 97,
    OrderID: 8,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Eire',
    Country: 'Thailand',
    Name: 'ML Road Frame',
    SellDate: '10/04/2025',
    Phone: '45-1186054',
    InStock: true,
    Quantity: 161,
    OrderID: 1,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Vinte',
    Country: 'United Kingdom',
    Name: 'ML Road Frame-W',
    SellDate: '22/01/2025',
    Phone: '62-6202742',
    InStock: true,
    Quantity: 58,
    OrderID: 4,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Twitterlist',
    Country: 'China',
    Name: 'Mountain Bike Socks',
    SellDate: '09/11/2025',
    Phone: '88-9646223',
    InStock: true,
    Quantity: 92,
    OrderID: 8,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Eidel',
    Country: 'Bangladesh',
    Name: 'Mountain-100',
    SellDate: '19/09/2025',
    Phone: '45-5588112',
    InStock: true,
    Quantity: 5,
    OrderID: 6,
    B: 5,
  },
  {
    Selected: false,
    CompanyName: 'Trunyx',
    Country: 'Nigeria',
    Name: 'Mountain-200',
    SellDate: '09/03/2025',
    Phone: '66-6271819',
    InStock: true,
    Quantity: 158,
    OrderID: 4,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Katz',
    Country: 'Turkey',
    Name: 'Mountain-300',
    SellDate: '05/03/2025',
    Phone: '38-9245023',
    InStock: false,
    Quantity: 121,
    OrderID: 5,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Kaymbo',
    Country: 'United States',
    Name: 'Mountain-400-W',
    SellDate: '24/12/2025',
    Phone: '44-5916927',
    InStock: false,
    Quantity: 61,
    OrderID: 5,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Ozu',
    Country: 'Pakistan',
    Name: 'Mountain-500',
    SellDate: '13/06/2025',
    Phone: '31-5449914',
    InStock: true,
    Quantity: 155,
    OrderID: 2,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Rhynyx',
    Country: 'India',
    Name: 'Racing Socks',
    SellDate: '05/12/2025',
    Phone: '19-9413869',
    InStock: true,
    Quantity: 162,
    OrderID: 2,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Flashset',
    Country: 'Iran',
    Name: 'Road-150',
    SellDate: '14/12/2025',
    Phone: '25-9807605',
    InStock: false,
    Quantity: 46,
    OrderID: 7,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Yata',
    Country: 'Congo (Kinshasa)',
    Name: 'Road-250',
    SellDate: '12/06/2025',
    Phone: '74-4291983',
    InStock: true,
    Quantity: 47,
    OrderID: 4,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Brainlounge',
    Country: 'Vietnam',
    Name: 'Road-350-W',
    SellDate: '10/03/2025',
    Phone: '83-0980643',
    InStock: true,
    Quantity: 104,
    OrderID: 2,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Babblestorm',
    Country: 'United States',
    Name: 'Road-450',
    SellDate: '10/10/2025',
    Phone: '19-2878430',
    InStock: true,
    Quantity: 101,
    OrderID: 6,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Youspan',
    Country: 'Brazil',
    Name: 'Road-550-W',
    SellDate: '16/12/2025',
    Phone: '19-1838230',
    InStock: true,
    Quantity: 150,
    OrderID: 10,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Nlounge',
    Country: 'China',
    Name: 'Road-650',
    SellDate: '31/10/2025',
    Phone: '32-2267938',
    InStock: true,
    Quantity: 42,
    OrderID: 4,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Twinte',
    Country: 'India',
    Name: 'Road-750',
    SellDate: '17/08/2025',
    Phone: '79-2821972',
    InStock: true,
    Quantity: 144,
    OrderID: 9,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Oyonder',
    Country: 'United Kingdom',
    Name: 'Short-Sleeve Classic Jersey',
    SellDate: '04/12/2025',
    Phone: '46-6597557',
    InStock: true,
    Quantity: 195,
    OrderID: 4,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Gigabox',
    Country: 'Pakistan',
    Name: 'Sport-100',
    SellDate: '03/02/2025',
    Phone: '15-1793960',
    InStock: true,
    Quantity: 199,
    OrderID: 4,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Livetube',
    Country: 'France',
    Name: 'Touring-1000',
    SellDate: '16/05/2025',
    Phone: '86-0811003',
    InStock: true,
    Quantity: 110,
    OrderID: 4,
    B: 5,
  },
  {
    Selected: false,
    CompanyName: 'Voomm',
    Country: 'United Kingdom',
    Name: 'Touring-2000',
    SellDate: '15/07/2025',
    Phone: '95-3068680',
    InStock: true,
    Quantity: 51,
    OrderID: 4,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Voonyx',
    Country: 'China',
    Name: 'Touring-3000',
    SellDate: '27/11/2025',
    Phone: '35-3085360',
    InStock: false,
    Quantity: 69,
    OrderID: 2,
    B: 5,
  },
  {
    Selected: false,
    CompanyName: 'Zoombeat',
    Country: 'United States',
    Name: "Women's Mountain Shorts",
    SellDate: '03/11/2025',
    Phone: '56-8673088',
    InStock: false,
    Quantity: 53,
    OrderID: 2,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Roomm',
    Country: 'China',
    Name: "Women's Tights",
    SellDate: '16/03/2025',
    Phone: '76-0085918',
    InStock: true,
    Quantity: 168,
    OrderID: 1,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Leenti',
    Country: 'China',
    Name: 'Mountain-400',
    SellDate: '16/05/2025',
    Phone: '03-0893276',
    InStock: false,
    Quantity: 58,
    OrderID: 1,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Jetpulse',
    Country: 'United States',
    Name: 'Road-550',
    SellDate: '08/02/2025',
    Phone: '79-9013306',
    InStock: true,
    Quantity: 152,
    OrderID: 9,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Katz',
    Country: 'Peru',
    Name: 'Road-350',
    SellDate: '15/02/2025',
    Phone: '55-7799920',
    InStock: true,
    Quantity: 66,
    OrderID: 4,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Cogidoo',
    Country: 'India',
    Name: 'LL Mountain Front Wheel',
    SellDate: '04/06/2025',
    Phone: '07-0881122',
    InStock: false,
    Quantity: 112,
    OrderID: 9,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Divavu',
    Country: 'Colombia',
    Name: 'Touring Rear Wheel',
    SellDate: '24/02/2025',
    Phone: '58-6157387',
    InStock: true,
    Quantity: 50,
    OrderID: 10,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Mydeo',
    Country: 'China',
    Name: 'Touring Front Wheel',
    SellDate: '07/12/2025',
    Phone: '12-2810010',
    InStock: false,
    Quantity: 31,
    OrderID: 3,
    B: 5,
  },
  {
    Selected: false,
    CompanyName: 'Browsebug',
    Country: 'Japan',
    Name: 'ML Mountain Front Wheel',
    SellDate: '14/01/2025',
    Phone: '64-9249984',
    InStock: true,
    Quantity: 132,
    OrderID: 5,
    B: 5,
  },
  {
    Selected: false,
    CompanyName: 'Layo',
    Country: 'China',
    Name: 'HL Mountain Front Wheel',
    SellDate: '24/04/2025',
    Phone: '45-0739652',
    InStock: true,
    Quantity: 45,
    OrderID: 1,
    B: 5,
  },
  {
    Selected: false,
    CompanyName: 'Snaptags',
    Country: 'United Kingdom',
    Name: 'LL Touring Handlebars',
    SellDate: '06/08/2025',
    Phone: '09-5712761',
    InStock: true,
    Quantity: 197,
    OrderID: 4,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Cogilith',
    Country: 'China',
    Name: 'HL Touring Handlebars',
    SellDate: '31/05/2025',
    Phone: '01-7345008',
    InStock: true,
    Quantity: 190,
    OrderID: 4,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Reallinks',
    Country: 'United Kingdom',
    Name: 'LL Road Front Wheel',
    SellDate: '14/05/2025',
    Phone: '62-1065350',
    InStock: true,
    Quantity: 184,
    OrderID: 3,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Quaxo',
    Country: 'United States',
    Name: 'ML Road Front Wheel',
    SellDate: '23/03/2025',
    Phone: '44-7241323',
    InStock: true,
    Quantity: 169,
    OrderID: 3,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Devify',
    Country: 'China',
    Name: 'HL Road Front Wheel',
    SellDate: '12/12/2025',
    Phone: '52-0295699',
    InStock: false,
    Quantity: 152,
    OrderID: 4,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Youopia',
    Country: 'Angola',
    Name: 'LL Mountain Handlebars',
    SellDate: '01/04/2025',
    Phone: '52-2650922',
    InStock: false,
    Quantity: 182,
    OrderID: 6,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Ainyx',
    Country: 'China',
    Name: 'Touring Pedal',
    SellDate: '27/02/2025',
    Phone: '48-3618525',
    InStock: true,
    Quantity: 141,
    OrderID: 6,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Browsetype',
    Country: 'Malaysia',
    Name: 'ML Mountain Handlebars',
    SellDate: '28/04/2025',
    Phone: '51-8893923',
    InStock: true,
    Quantity: 169,
    OrderID: 7,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Muxo',
    Country: 'China',
    Name: 'HL Mountain Handlebars',
    SellDate: '22/08/2025',
    Phone: '68-5911361',
    InStock: false,
    Quantity: 39,
    OrderID: 7,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Bubbletube',
    Country: 'China',
    Name: 'LL Road Handlebars',
    SellDate: '04/10/2025',
    Phone: '41-5880042',
    InStock: true,
    Quantity: 71,
    OrderID: 8,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Fadeo',
    Country: 'Vietnam',
    Name: 'ML Road Handlebars',
    SellDate: '23/04/2025',
    Phone: '90-5913983',
    InStock: true,
    Quantity: 148,
    OrderID: 10,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Yadel',
    Country: 'United Kingdom',
    Name: 'HL Road Handlebars',
    SellDate: '18/04/2025',
    Phone: '92-0960699',
    InStock: true,
    Quantity: 116,
    OrderID: 8,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Blognation',
    Country: 'China',
    Name: 'LL Headset',
    SellDate: '10/01/2025',
    Phone: '06-9493898',
    InStock: true,
    Quantity: 96,
    OrderID: 10,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Devpoint',
    Country: 'China',
    Name: 'ML Headset',
    SellDate: '25/12/2025',
    Phone: '69-5878565',
    InStock: true,
    Quantity: 35,
    OrderID: 4,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Aibox',
    Country: 'United Kingdom',
    Name: 'HL Headset',
    SellDate: '18/03/2025',
    Phone: '13-1133017',
    InStock: true,
    Quantity: 16,
    OrderID: 8,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Brightdog',
    Country: 'China',
    Name: 'LL Mountain Pedal',
    SellDate: '11/09/2025',
    Phone: '39-6530433',
    InStock: true,
    Quantity: 194,
    OrderID: 2,
    B: 5,
  },
  {
    Selected: false,
    CompanyName: 'Gabcube',
    Country: 'Nigeria',
    Name: 'ML Mountain Pedal',
    SellDate: '22/04/2025',
    Phone: '96-6860388',
    InStock: true,
    Quantity: 24,
    OrderID: 1,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Muxo',
    Country: 'China',
    Name: 'HL Mountain Pedal',
    SellDate: '05/06/2025',
    Phone: '30-0356137',
    InStock: true,
    Quantity: 170,
    OrderID: 4,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Tambee',
    Country: 'China',
    Name: 'ML Touring Seat/Saddle',
    SellDate: '22/02/2025',
    Phone: '93-9058255',
    InStock: true,
    Quantity: 184,
    OrderID: 9,
    B: 5,
  },
  {
    Selected: false,
    CompanyName: 'Cogilith',
    Country: 'India',
    Name: 'LL Touring Seat/Saddle',
    SellDate: '06/04/2025',
    Phone: '82-9268909',
    InStock: false,
    Quantity: 153,
    OrderID: 10,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Dynabox',
    Country: 'Hong Kong',
    Name: 'HL Touring Seat/Saddle',
    SellDate: '10/01/2025',
    Phone: '20-6913815',
    InStock: false,
    Quantity: 88,
    OrderID: 10,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Shuffledrive',
    Country: 'Sudan',
    Name: 'LL Road Pedal',
    SellDate: '16/09/2025',
    Phone: '08-8238817',
    InStock: true,
    Quantity: 57,
    OrderID: 9,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Fivechat',
    Country: 'China',
    Name: 'ML Road Pedal',
    SellDate: '26/08/2025',
    Phone: '44-7370350',
    InStock: false,
    Quantity: 62,
    OrderID: 4,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Meembee',
    Country: 'United States',
    Name: 'HL Road Pedal',
    SellDate: '27/12/2025',
    Phone: '01-3525949',
    InStock: true,
    Quantity: 123,
    OrderID: 2,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Dynazzy',
    Country: 'United Kingdom',
    Name: 'LL Mountain Seat/Saddle 1',
    SellDate: '15/12/2025',
    Phone: '04-2414623',
    InStock: true,
    Quantity: 77,
    OrderID: 10,
    B: 5,
  },
  {
    Selected: false,
    CompanyName: 'Eare',
    Country: 'China',
    Name: 'ML Mountain Seat/Saddle 1',
    SellDate: '04/04/2025',
    Phone: '15-1917509',
    InStock: false,
    Quantity: 199,
    OrderID: 9,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Yozio',
    Country: 'China',
    Name: 'HL Mountain Seat/Saddle 1',
    SellDate: '15/03/2025',
    Phone: '06-2526845',
    InStock: true,
    Quantity: 149,
    OrderID: 8,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Quinu',
    Country: "Xi'an",
    Name: '425-777-7829',
    SellDate: '22/02/2025',
    Phone: '83-1713558',
    InStock: false,
    Quantity: 191,
    OrderID: 9,
    B: 5,
  },
  {
    Selected: false,
    CompanyName: 'Jazzy',
    Country: 'United Kingdom',
    Name: 'ML Road Seat/Saddle 1',
    SellDate: '07/08/2025',
    Phone: '00-8892524',
    InStock: true,
    Quantity: 150,
    OrderID: 10,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Thoughtsphere',
    Country: 'China',
    Name: 'HL Road Seat/Saddle 1',
    SellDate: '28/11/2025',
    Phone: '39-5538991',
    InStock: true,
    Quantity: 130,
    OrderID: 7,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Leenti',
    Country: 'China',
    Name: 'ML Road Rear Wheel',
    SellDate: '29/12/2025',
    Phone: '06-9002973',
    InStock: true,
    Quantity: 179,
    OrderID: 1,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Quaxo',
    Country: 'United Kingdom',
    Name: 'HL Road Rear Wheel',
    SellDate: '06/09/2025',
    Phone: '73-6104901',
    InStock: true,
    Quantity: 98,
    OrderID: 5,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Tanoodle',
    Country: 'Chile',
    Name: 'LL Mountain Seat/Saddle 2',
    SellDate: '24/05/2025',
    Phone: '68-7384479',
    InStock: true,
    Quantity: 175,
    OrderID: 2,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Feednation',
    Country: 'China',
    Name: 'ML Mountain Seat/Saddle 2',
    SellDate: '21/11/2025',
    Phone: '26-7757763',
    InStock: true,
    Quantity: 11,
    OrderID: 1,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Kayveo',
    Country: 'China',
    Name: 'HL Mountain Seat/Saddle 2',
    SellDate: '21/06/2025',
    Phone: '07-4873562',
    InStock: false,
    Quantity: 184,
    OrderID: 7,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Meevee',
    Country: 'Saudi Arabia',
    Name: 'LL Road Seat/Saddle 1',
    SellDate: '16/11/2025',
    Phone: '46-5819554',
    InStock: false,
    Quantity: 27,
    OrderID: 9,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Twitterworks',
    Country: 'China',
    Name: 'ML Road Seat/Saddle 2',
    SellDate: '19/04/2025',
    Phone: '01-2666826',
    InStock: true,
    Quantity: 186,
    OrderID: 3,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Wikizz',
    Country: 'Tanzania',
    Name: 'HL Road Seat/Saddle 2',
    SellDate: '08/03/2025',
    Phone: '54-7090503',
    InStock: true,
    Quantity: 20,
    OrderID: 3,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Yoveo',
    Country: 'United States',
    Name: 'LL Mountain Tire',
    SellDate: '14/10/2025',
    Phone: '78-7658520',
    InStock: false,
    Quantity: 153,
    OrderID: 2,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Yakidoo',
    Country: 'China',
    Name: 'ML Mountain Tire',
    SellDate: '12/10/2025',
    Phone: '23-9926318',
    InStock: true,
    Quantity: 161,
    OrderID: 8,
    B: 5,
  },
  {
    Selected: false,
    CompanyName: 'Oyope',
    Country: 'China',
    Name: 'HL Mountain Tire',
    SellDate: '20/09/2025',
    Phone: '20-0179517',
    InStock: true,
    Quantity: 98,
    OrderID: 10,
    B: 5,
  },
  {
    Selected: false,
    CompanyName: 'Skipstorm',
    Country: 'United States',
    Name: 'LL Road Tire',
    SellDate: '01/10/2025',
    Phone: '02-9543343',
    InStock: true,
    Quantity: 30,
    OrderID: 7,
    B: 3,
  },
  {
    Selected: false,
    CompanyName: 'Minyx',
    Country: 'United States',
    Name: 'ML Road Tire',
    SellDate: '07/07/2025',
    Phone: '98-3938169',
    InStock: true,
    Quantity: 73,
    OrderID: 10,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Miboo',
    Country: 'China',
    Name: 'HL Road Tire',
    SellDate: '25/07/2025',
    Phone: '68-5197934',
    InStock: true,
    Quantity: 158,
    OrderID: 9,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Realfire',
    Country: 'United States',
    Name: 'Touring Tire',
    SellDate: '27/08/2025',
    Phone: '39-8260460',
    InStock: true,
    Quantity: 122,
    OrderID: 5,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Shufflester',
    Country: 'China',
    Name: 'Mountain Tire Tube',
    SellDate: '08/06/2025',
    Phone: '45-9776170',
    InStock: true,
    Quantity: 33,
    OrderID: 2,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Ntag',
    Country: 'China',
    Name: 'Road Tire Tube',
    SellDate: '06/12/2025',
    Phone: '45-0858451',
    InStock: true,
    Quantity: 107,
    OrderID: 6,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Jabberbean',
    Country: 'United States',
    Name: 'Touring Tire Tube',
    SellDate: '26/04/2025',
    Phone: '15-4247305',
    InStock: true,
    Quantity: 15,
    OrderID: 1,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Thoughtblab',
    Country: 'China',
    Name: 'LL Bottom Bracket',
    SellDate: '21/05/2025',
    Phone: '15-8534931',
    InStock: true,
    Quantity: 168,
    OrderID: 5,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Jabbertype',
    Country: 'China',
    Name: 'Classic Vest',
    SellDate: '25/07/2025',
    Phone: '23-1251557',
    InStock: true,
    Quantity: 135,
    OrderID: 4,
    B: 2,
  },
  {
    Selected: false,
    CompanyName: 'Buzzshare',
    Country: 'United Kingdom',
    Name: 'Cycling Cap',
    SellDate: '07/07/2025',
    Phone: '86-5920601',
    InStock: true,
    Quantity: 11,
    OrderID: 1,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Roodel',
    Country: 'United States',
    Name: 'Full-Finger Gloves',
    SellDate: '13/01/2025',
    Phone: '48-1055459',
    InStock: true,
    Quantity: 41,
    OrderID: 6,
    B: 4,
  },
  {
    Selected: false,
    CompanyName: 'Zoovu',
    Country: 'China',
    Name: 'Half-Finger Gloves',
    SellDate: '03/06/2025',
    Phone: '12-7842022',
    InStock: true,
    Quantity: 144,
    OrderID: 6,
    B: 1,
  },
  {
    Selected: false,
    CompanyName: 'Photofeed',
    Country: 'China',
    Name: 'HL Mountain Frame',
    SellDate: '14/07/2025',
    Phone: '94-5088099',
    InStock: true,
    Quantity: 106,
    OrderID: 1,
    B: 4,
  },
]
